COMP231W21-G3/COMP231W21_G3_PHONNECT

readme.md, readme.txt, server/client/src/App.js, server/client/src/components/Navbar.js
=> Added UI screens for Group  Chat Message and Search User for Group Chat

server/models/post.js, server/routes/chatroom.js
@vuhieuphong  please review chatroom. I have added route for all chats
=> Code real-time route to get all chats belonging to selected chatroom

server/models/chatroom.js
@vuhieuphong please review. I added a model for chatroom.
=> Write a database schema for Group Chat

server/client/src/App.css, server/client/src/App.js, server/client/src/components/screens/MeetAStranger.js
Created MeetAStranger.js and added to app.js routes
=> Created MeetAStranger UI

server/client/public/mappings/speechmapping.xml, server/client/src/components/screens/VoiceCommand.js
* Added Speech Synthesis for voice back
* Added response and suggestion feedback mappings
=> Added Speech Synthesis and Response/Suggestion Loop for Voice Commands

server/client/src/App.js, server/client/src/components/screens/UserProfile.js
Added UI interface "UserProfile.js" for other user's profile
=> Added UserProfile UI screen

server/client/src/components/screens/UserProfile.js
Updated UserProfile.js to show list of followers and people that user is following
=> Added Followers and Following List UI Screen

server/client/public/mappings/speechmapping.xml, server/client/src/components/screens/VoiceCommand.js
* Now using relative path for navigations
* Added "I'm sorry, I do not understand that command" when the input is completely unrecognizable
* Removed message mapping as I believe that is same as chatroom
=> Minor enhancements to Voice Command

server/client/src/components/screens/Chatrooms.js, server/client/src/components/screens/VoiceCommand.js, server/routes/chatroom.js
Please review my code. Thank you!
=> Added routes for Meet A Stranger

server/routes/post.js
=> route to new post created

server/routes/post.js
Added routing in post.js to show posts in user feed
=> Added routes to target posts for user feed

server/models/user.js
Added a schema for user in models/user.js
=> Write database schema for Account

server/client/src/App.js, server/client/src/components/screens/VoiceCommand.js
* App.js reducer and socket
* Removed 2 additional buttons
=> Added missing app.js components to load chatroom

server/routes/chatroom.js, server/routes/post.js
Added routes to get all posts, current users post and specific post by post id
=> Added routes to get all posts, current users post and specific post by post id

server/routes/chatroom.js
=> Added route to add multiple users and create a group chat

server/client/src/components/screens/Profile.js, server/client/src/components/screens/UserProfile.js
Please review my code. Thank you!
=> Bug fix for Own Profile and Others' Profile screens

server/client/src/components/HomePostOptions.js
Created a button on the posts for the user to edit post. Please review
=> Code a button on posts to redirect to Edit Post Screen

server/client/src/App.js, server/client/src/components/screens/EditPost.js
Edit post screen that allows user to change existing post
=> Merge "Code an Edit Post screen" into main

server/client/src/components/screens/Post.js
Added LIke/Unlike request function in Post.js
=> Code function to fetch request to like/unlike post

server/client/src/components/CommentsModal.js, server/client/src/components/screens/Post.js
Code route to add a comment to selected post
Code a delete comment button on personal comments in posts
Code function to fetch request to Unfollow User
=> Added routes, UI and functions for unfollow user and comments

server/client/src/components/Navbar.js
Code results list screen for search user profile
Code Sign in screen
=> Added UI screens for search user profile and sign in

server/client/src/App.js, server/client/src/components/screens/EditAccount.js, server/client/src/components/screens/EditPost.js, server/client/src/components/screens/Home.js, server/client/src/components/screens/Post.js
Also fixed few format issues and typos
=> Coded EditAccount UI screen

server/client/src/components/screens/Chatrooms.js
added button to add group chat member in chatroom
=> Code add group chat member button

server/client/src/components/HomePostOptions.js, server/client/src/components/screens/UserProfile.js
added unfollow user button and created route to edit a post
=> Code Unfollow User button / Code route to edit a post 
